[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["takakuni <takakuni>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.87"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
